name: Publish Docker Images

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build"
        required: true
      log_level:
        description: "Log level"
        required: false
        default: "info"

jobs:
  publish-to-dockerhub:
    name: Publish to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set VERSION ENV
        run: echo VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Make Image Tags
        run: |
          echo docker_hub_tag=${{ secrets.DOCKERHUB_USERNAME }}/opensca-cli >> ${GITHUB_ENV}
          echo github_package_tag=ghcr.io/${{ github.repository_owner }}/opensca-cli | tr '[:upper:]' '[:lower:]' >> ${GITHUB_ENV}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
          tags: |
            ${{ env.docker_hub_tag }}:latest
            ${{ env.docker_hub_tag }}:${{ env.VERSION }}
            ${{ env.github_package_tag }}:latest
            ${{ env.github_package_tag }}:${{ env.VERSION }}
