name: Publish Docker Images

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: true
      log_level:
        description: 'Log level'
        required: false
        default: 'info'


jobs:
  publish-to-dockerhub:
    name: Publish to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set VERSION ENV
        run: echo VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/opensca-cli:latest, ${{ secrets.DOCKERHUB_USERNAME }}/opensca-cli:${{ env.VERSION }}

  publish-to-github:
    name: Publish to Github
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set VERSION ENV
      run: echo VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
    - name: Convert to lowercase
      run: |
        echo latest_tag=ghcr.io/${{ github.repository_owner }}/opensca-cli:latest | tr '[:upper:]' '[:lower:]' >> ${GITHUB_ENV}
        echo version_tag=ghcr.io/${{ github.repository_owner }}/opensca-cli:${{ env.VERSION }} | tr '[:upper:]' '[:lower:]' >> ${GITHUB_ENV}
    - name: Print env variables
      run: |
        echo "GITHUB_REPOSITORY=${{ github.repository_owner }}"
        echo "LATEST_TAG=${{ env.latest_tag }}"
        echo "VERSION_TAG=${{ env.version_tag }}"
    - name: Build and push to GitHub Packages
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        build-args: |
          VERSION=${{ env.VERSION }}
        tags: ${{ env.latest_tag }}, ${{ env.version_tag }}
